name: Metrics Embed Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */7 * *' # This will run the workflow daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run Metrics Embed
      uses: lowlighter/metrics@latest
      with:
        # Required: GitHub token to access repository
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # Optional: Any other configuration for metrics
        user: BarryDam
        template: classic
        base: header, repositories, activity, community
        config_timezone: UTC+1
        plugin_isocalendar: yes
        plugin_isocalendar_duration: half-year
        plugin_languages: yes
        plugin_pagespeed: yes
        plugin_pagespeed_screenshot: yes
        plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
        plugin_topics: yes
        plugin_topics_mode: mastered
        plugin_topics_limit: 0